teams:
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - lanayanelson
  - minyu66
  - thelinuxfoundation
  - tykeal
- name: community
  maintainers:
  - ryjones
  members:
  - JFleenor
  - hartm
  - lanayanelson
  - tkuhrt
- name: security-managers
  maintainers:
  - hartm
  - ryjones
- name: tac
  maintainers:
  - tkuhrt
  members:
  - VRamakrishna
  - arsulegai
  - conor10
  - denyeart
  - jimthematrix
  - mbrandenburger
  - non-fungible-nelson
  - petermetz
  - swcurran
  - yacovm
repositories:
- name: governance
  teams:
    community: maintain
    tac: maintain
  visibility: public
- name: project-proposals
  teams:
    community: maintain
    security-managers: read
    tac: maintain
  visibility: public
- name: wiki
  teams:
    community: maintain
    lf-staff: maintain
  visibility: private
- name: wikix
  teams:
    community: maintain
    lf-staff: maintain
  visibility: private
