name: Send project report reminders
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
permissions:
  issues: write
jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the governance repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send due report reminders
        uses: hyperledger-tooling/github-issue-schedule@c11fdda5658aea8719f9ccb9bdc94763786822e7 # 1.4
        env:
          GITHUB_TOKEN: "${{ secrets.UPDATE_REMINDERS }}"
          CONFIG_FILE: ./.github/configs/project-report-reminders.yml
